//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Assignment_Fiza
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomerDetail
    {
        public int PK_Customer_ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Shoe_Type { get; set; }
        public string Shoe_Brand { get; set; }
        public string Shoe_Color { get; set; }
        public string Shoe_Size { get; set; }
        public Nullable<int> TotalBill { get; set; }
    }
}
